//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWebsite.RepositoryLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumsForum
    {
        public ForumsForum()
        {
            this.ForumsTopics = new HashSet<ForumsTopic>();
        }
    
        public int ForumID { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
    
        public virtual ICollection<ForumsTopic> ForumsTopics { get; set; }
    }
}
