//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWebsite.RepositoryLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumsTopic
    {
        public ForumsTopic()
        {
            this.ForumsPosts = new HashSet<ForumsPost>();
        }
    
        public int TopicID { get; set; }
        public int ForumID { get; set; }
        public string Title { get; set; }
    
        public virtual ForumsForum ForumsForum { get; set; }
        public virtual ICollection<ForumsPost> ForumsPosts { get; set; }
    }
}
