//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWebsite.RepositoryLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumsPost
    {
        public int PostID { get; set; }
        public int TopicID { get; set; }
        public string Content { get; set; }
        public bool IsBasePost { get; set; }
        public int UserID { get; set; }
        public string IP { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime EditDate { get; set; }
    
        public virtual ForumsTopic ForumsTopic { get; set; }
        public virtual WebsiteUser WebsiteUser { get; set; }
    }
}
