//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWebsite.RepositoryLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update
    {
        public int UpdateID { get; set; }
        public string VersionNum { get; set; }
        public string Comment { get; set; }
        public string UpdateNotes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    }
}
