//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWebsite.RepositoryLayer.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteDatabaseEntities : DbContext
    {
        public WebsiteDatabaseEntities()
            : base("name=WebsiteDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Update> Updates { get; set; }
        public virtual DbSet<MediaScreenshot> MediaScreenshots { get; set; }
        public virtual DbSet<ForumsForum> ForumsForums { get; set; }
        public virtual DbSet<ForumsPost> ForumsPosts { get; set; }
        public virtual DbSet<ForumsTopic> ForumsTopics { get; set; }
        public virtual DbSet<WebsiteUser> WebsiteUsers { get; set; }
    }
}
