//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWebsite.RepositoryLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUser
    {
        public WebsiteUser()
        {
            this.ForumsPosts = new HashSet<ForumsPost>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string HashedPassword { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
    
        public virtual ICollection<ForumsPost> ForumsPosts { get; set; }
    }
}
