using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TemplateWebsite.Shared.Repository;
using TemplateWebsite.Shared.Models;
using TemplateWebsite.RepositoryLayer.Entities;
using TemplateWebsite.RepositoryLayer.Converters;

namespace TemplateWebsite.RepositoryLayer.Repository 
{
    public class ForumsPostRepository : BaseRepository, IForumsPostRepository 
    {
        public List<ModelForumsPost> GetAllPostsOfTopic(int topicID) {
            var entities = dbContext.ForumsPosts.Where(p => p.TopicID == topicID);
            List<ModelForumsPost> models = new List<ModelForumsPost>();

            //only convert and find additional data if some posts were found
            if (entities.Count() > 0) {
                foreach (var entity in entities) {
                    models.Add(GetExtraPostData(entity));
                };
            }
            return models;
        }
        public ModelForumsPost GetPost(int postID) {
            var entity = dbContext.ForumsPosts.SingleOrDefault(p => p.PostID == postID);
            ModelForumsPost model;

            //only convert and find additional data if the post was found
            if (entity != null) {
                model = GetExtraPostData(entity);
            } else {
                model = new ModelForumsPost();
            }
            return model;
        }
        internal ModelForumsPost GetExtraPostData(ForumsPost entity) {
            string posterName = dbContext.WebsiteUsers.Where(w => w.UserID == entity.UserID).Select(w => w.Username).FirstOrDefault();
            return entity.ConvertEntityToModel(dbContext, posterName);
        }
        public int AddPost(ModelForumsPost model) {
            using (WebsiteDatabaseEntities insertContext = new WebsiteDatabaseEntities()) {
                var entity = model.ConvertModelToEntity(insertContext);
                insertContext.ForumsPosts.Add(entity);
                insertContext.SaveChanges();
                return entity.PostID;  //auto-generated by the database when .SaveChanges() is called
            }
        }
    }
}
